### version
GET https://0.0.0.0:8081/version
Accept: application/json

### health
GET https://0.0.0.0:8081/api/health
Accept: application/json

### readiness
GET https://0.0.0.0:8081/api/health/readiness
Accept: application/json

### register
POST https://0.0.0.0:8081/api/v1/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### login
POST https://0.0.0.0:8081/api/v1/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

### me
GET https://0.0.0.0:8081/api/v1/restricted/me
Cookie: session=OI9xh0IhnmI8KaTowW_THdnO0CqE1WP0N4bbydiR4ss;

### list of expenses, by default gets the 1st 10 expenses ordered by trx date desc
GET https://0.0.0.0:8081/api/v1/expense
Accept: application/json

### list of paginated expenses
GET https://0.0.0.0:8081/api/v1/expense?page=1&size=5
Accept: application/json

### list of paginated expenses with search
GET https://0.0.0.0:8081/api/v1/expense?page=1&size=5&title=tes
Accept: application/json

### list of paginated expenses filter by date
GET https://0.0.0.0:8081/api/v1/expense?page=1&size=5&year=2023&month=7
Accept: application/json

### expense by id
GET https://0.0.0.0:8081/api/v1/expense/3
Accept: application/json

### create an expense
POST https://0.0.0.0:8081/api/v1/expense
Content-Type: application/json

{
  "title": "Test",
  "amount": -300,
  "currency_code": "USD",
  "transaction_date": "2023-09-03T15:04:05.123499999Z"
}

### edit an expense
PUT https://0.0.0.0:8081/api/v1/expense/6ca8af0c-9446-4371-8d48-86db80bf44f2
Content-Type: application/json

{
  "title": "Test",
  "amount": 200,
  "currency_code": "MYR",
  "transaction_date": "2023-09-01T15:04:05.123499999Z"
}

### delete an expense
DELETE https://0.0.0.0:8081/api/v1/expense/1
Accept: application/json

### total expenses filtered by date
GET https://0.0.0.0:8081/api/v1/expense/total?year=2023&month=7
Accept: application/json

### total expenses by default return today's total
GET https://0.0.0.0:8081/api/v1/expense/total?currency=myr
Accept: application/json

### average expenses by default return today's average
GET https://0.0.0.0:8081/api/v1/expense/average?currency=myr
Accept: application/json

